### ISSUE TITLE
Smart path tool

### ISSUE THREAD

**Issue by yenatch** [yenatch/pretmap#43]
Right-click select is not very discoverable.

**Comment by ProjectRevoTPP** [comment]
Isn't this in already?

**Comment by yenatch** [comment]
My thinking was it would be a separate tool next to the pencil. A checkbox would also work, but it might clutter the tile window.

**Comment by huderlem** [comment]
#55 moved the smart-path mode into a checkbox.  Can probably close this issue.  I don't think a separate tool makes sense, especially since smart-path is used by floodfill, too.
