### ISSUE TITLE
Ability to import maps from another ROM

### ISSUE THREAD

**Issue by ProjectRevoTPP** [yenatch/pretmap#47]
To make pretmap usable for dissassemblies, we need to implement an "Import" feature that tries to target a ROM (usually a ROM hack) with the same base (read the ROM header) and try to replace the dissassembly's maps with the dumped maps, automatically naming all the Maps and MapGroups 00, 01, 02, etc.

This will make it actually feasible for people to more easily transfer their rom hack bases to a dissassembly.

**Comment by RevoSucks** [comment]
"Probably separate. I think this feature might only be useful for a rather short time period." @huderlem
